### ISSUE TITLE
memory leak detected

### ISSUE THREAD

**Issue by kimmobrunfeldt** [kimmobrunfeldt/chokidar-cli#1]
```
> components-for-todays-web@0.0.0 build-less /Users/kbru/code/personal/components-for-todays-web
> lessc src/main.less src/bundle.css && npm run autoprefixer


> components-for-todays-web@0.0.0 autoprefixer /Users/kbru/code/personal/components-for-todays-web
> autoprefixer src/bundle.css

change:src/button/button.less
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.EventEmitter.addListener (events.js:179:15)
    at ReadStream.Readable.on (_stream_readable.js:667:33)
    at ReadStream.EventEmitter.once (events.js:204:8)
    at Socket.Readable.pipe (_stream_readable.js:576:8)
    at Object.run (/Users/kbru/code/personal/components-for-todays-web/node_modules/chokidar-cli/utils.js:32:21)
    at run (/Users/kbru/code/personal/components-for-todays-web/node_modules/chokidar-cli/index.js:168:18)
    at delayed [as _onTimeout] (/Users/kbru/code/personal/components-for-todays-web/node_modules/chokidar-cli/node_modules/lodash/index.js:7707:27)
    at Timer.listOnTimeout (timers.js:133:15)

> components-for-todays-web@0.0.0 build-less /Users/kbru/code/personal/components-for-todays-web
> lessc src/main.less src/bundle.css && npm run autoprefixer
```

**Comment by kimmobrunfeldt** [comment]
Haven't seen this anymore.
