### ISSUE TITLE
Error with -c command

### ISSUE THREAD

**Issue by CaitlinWeb** [kimmobrunfeldt/chokidar-cli#4]
First, some background: I'm using npm as a task runner, and I'd been using [watch](https://www.npmjs.com/package/watch) but I heard `chokidar` is more efficient. I tried `chokidar-cli` installed both locally to my project and globally. Unfortunately I'm getting the following error:
```
> chokidar "dev" -c "npm run dev"

Watching "dev" ..
change:dev\Controller.js
Error when executing npm run dev
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```
I have no idea what this means. I tried other commands, such as `cd ..`, but still get an error. Could anyone help me out?

**Comment by kimmobrunfeldt** [comment]
Sorry, haven't seen the issues as I've not been watching the repo. I'm also using chokidar like that, but I haven't seen that error before.

**Comment by tyrsius** [comment]
I'm also seeing this issue. I am on Windows 8

**Comment by kimmobrunfeldt** [comment]
Are you running chokidar from the root of the project where the package.json is?

**Comment by CaitlinWeb** [comment]
@kimmobrunfeldt Yes. I tried running it in the project directory and from npm, same result. (I haven't updated and tried again since my original post, though.)

**Comment by kimmobrunfeldt** [comment]
Could you try this with the newest version(1.0.1) ?

**Comment by kimmobrunfeldt** [comment]
Closing because of inactivity.
