### ISSUE TITLE
Error: spawn /bin/false ENOENT

### ISSUE THREAD

**Issue by jsepia** [kimmobrunfeldt/chokidar-cli#46]
I'm getting an error when trying to run Chokidar.

## My `package.json`

```json
"scripts": {
    "build": "rollup -c",
    "watch:js": "chokidar --initial 'src/js/**/*.js' -c 'npm run build'"
},
```

## Command

  npm run watch:js

## Output

```
...
add:src/js/util/RNG.js
add:src/js/util/enum.js
add:src/js/util/id.js
add:src/js/util/log.js
Watching "src/js/**/*.js" ..
Error when executing npm run build
Error: spawn /bin/false ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

## Additional details

* **chokidar-cli:** `1.2.0`
* **node:** `v4.4.7`
* **OS:** OS X El Capitan version 10.11.6

**Comment by rfgamaral** [comment]
I'm having the same issue.

What issue is this a duplicate from? And is there a workaround one could use in the meantime?

**Comment by merrywhether** [comment]
I've run into the same issue on 10.13.6 with latest, even trying `echo 'test'` as the command throws.
